cpu-bind=MASK - bp1-gpu007, task  0  0 [169449]: mask 0x1010 set
2023-04-27 03:00:39.880218: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-27 03:00:41.130764: I tensorflow/core/common_runtime/gpu/gpu_process_state.cc:214] Using CUDA malloc Async allocator for GPU: 0
2023-04-27 03:00:41.131013: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9638 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:86:00.0, compute capability: 7.5
2023-04-27 03:00:41.131722: I tensorflow/core/common_runtime/gpu/gpu_process_state.cc:214] Using CUDA malloc Async allocator for GPU: 1
2023-04-27 03:00:41.131815: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 9638 MB memory:  -> device: 1, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:af:00.0, compute capability: 7.5
2023-04-27 03:01:32.844583: I tensorflow/stream_executor/cuda/cuda_dnn.cc:366] Loaded cuDNN version 8101
WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.reshape.Reshape object at 0x7f7fa59e2100>, because it is not built.
2023-04-27 14:49:03.139324: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:absl:Found untraced functions such as positional_embedding_layer_call_fn, positional_embedding_layer_call_and_return_conditional_losses, dropout_layer_call_fn, dropout_layer_call_and_return_conditional_losses, positional_embedding_1_layer_call_fn while saving (showing 5 of 790). These functions will not be directly callable after loading.
Traceback (most recent call last):
  File "/user/work/eh19257/ChampSimBPUModelling/models/2_bit_model_tf_transformer.py", line 715, in <module>
    transformer.save(sys.argv[6], save_format='tf')
  File "/sw/lang/anaconda.3.9.7-2021.12-tensorflow.2.7.0/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/sw/lang/anaconda.3.9.7-2021.12-tensorflow.2.7.0/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/sw/lang/anaconda.3.9.7-2021.12-tensorflow.2.7.0/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: Unable to serialize [[ 0.          0.          0.         ...  1.          1.
   1.        ]
 [ 0.84147096  0.68156135  0.53316844 ...  1.          1.
   1.        ]
 [ 0.9092974   0.99748     0.9021307  ...  0.9999999   0.99999994
   0.99999994]
 ...
 [ 0.17589758  0.4227187   0.1643498  ...  0.8847002   0.9346019
   0.96304584]
 [-0.7333133   0.9270015   0.6649599  ...  0.8845896   0.9345386
   0.9630099 ]
 [-0.9683193   0.9339683   0.9607745  ...  0.884479    0.9344753
   0.96297395]] to JSON. Unrecognized type <class 'tensorflow.python.framework.ops.EagerTensor'>.
